# Generated by Django 4.0 on 2021-12-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Navbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': 'منوی سایت', 'verbose_name_plural': 'آیتم ها'},
        ),
        migrations.AddField(
            model_name='navbar',
            name='active',
            field=models.BooleanField(default=False, verbose_name='نمایش داده شود'),
        ),
    ]
