# Generated by Django 4.0 on 2022-01-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='gender', max_length=4),
        ),
    ]
