# Generated by Django 4.0 on 2022-01-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Accounts', '0002_remove_profile_phone_number_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-user.png', null=True, upload_to='profile_pic/'),
        ),
    ]
