# Generated by Django 3.2.11 on 2022-01-28 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Market_Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='تیتر تخفیف')),
                ('description', models.TextField(verbose_name='توضیحات تخفیف')),
                ('image', models.ImageField(upload_to='OFF_Banners')),
                ('go_to', models.CharField(default='/Go_to_That_Page', max_length=100, verbose_name='هدایت شود به')),
                ('text_button', models.CharField(max_length=30, verbose_name='متن دکمه بنر تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='نمایش داده شود')),
            ],
        ),
        migrations.CreateModel(
            name='OFFProduct_limit_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discout_percent', models.IntegerField()),
                ('active', models.BooleanField(default=False, verbose_name='نمایش داده شود')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Market_Product.product')),
            ],
        ),
    ]
