# Generated by Django 4.0 on 2022-01-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market_OFFs_Banners', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OFFProduct_limit_time',
        ),
    ]
