# Generated by Django 4.0 on 2022-01-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0022_alter_review_status'),
        ('Market_OFFs_Banners', '0002_delete_offproduct_limit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OFFProduct_limit_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discout_percent', models.IntegerField()),
                ('active', models.BooleanField(default=False, verbose_name='نمایش داده شود')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Market_Product.product')),
            ],
        ),
    ]
