# Generated by Django 4.0 on 2021-12-23 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('url_name', models.CharField(max_length=150, verbose_name='نشانی در نوار آدرس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Categories_images')),
                ('slug', models.CharField(default='SLUG', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='تصویر')),
                ('color', models.CharField(default='رنگ هایی که بیشتر در محصول استفاده شده را وارد کنید', max_length=150, verbose_name='رنگ')),
                ('slug', models.SlugField(default='SLUG', max_length=100)),
                ('used_in', models.CharField(default='این محصول در چه زمینه هایی استفاده می شود ؟', max_length=450, verbose_name='موارد استفاده')),
                ('off_sale', models.IntegerField(default='0', verbose_name='تخفیف(مقدار تخفیف)')),
                ('active', models.BooleanField(default=False, verbose_name='موجود / ناموجود')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Product.category')),
            ],
        ),
    ]
