# Generated by Django 3.2.11 on 2022-01-28 04:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام برند')),
                ('logo', models.ImageField(upload_to='brand_logos', verbose_name='نشان تجاری')),
                ('about', ckeditor.fields.RichTextField(verbose_name='درباره')),
                ('website', models.URLField(null=True, verbose_name='لینک وب سایت این برند')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='نام')),
                ('url_name', models.CharField(max_length=150, verbose_name='نشانی در نوار آدرس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Categories_images')),
                ('slug', models.CharField(default='SLUG', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='نام')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='تصویر')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True)),
                ('off_sale', models.IntegerField(default='0', verbose_name='تخفیف(مقدار تخفیف)')),
                ('active', models.BooleanField(default=False, verbose_name='موجود / ناموجود')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='نام سایز')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=1)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('wating_for_published', 'در انتظار تایید'), ('True', 'تایید شده'), ('False', 'تایید نشده')], default='wating_for_published', max_length=20)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='Market_Product.Size', verbose_name='سایزهای موجود'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Market_Product.Tag', verbose_name='برچسب ها'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر کالا')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Product.product')),
            ],
        ),
    ]
