# Generated by Django 3.2.11 on 2022-01-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='about',
        ),
    ]
