# Generated by Django 4.0 on 2021-12-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
