# Generated by Django 3.2.11 on 2022-01-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0002_remove_brand_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
