# Generated by Django 3.2.11 on 2022-01-28 05:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0003_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام کمپانی')),
                ('about', ckeditor.fields.RichTextField(verbose_name='درباره')),
            ],
        ),
    ]
