# Generated by Django 4.0 on 2021-12-25 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
