# Generated by Django 4.0 on 2021-12-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0004_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
