# Generated by Django 3.2.11 on 2022-01-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0005_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featuers',
            field=models.TextField(default='ویژگی های محصول را با علامت (،) از هم جدا کنید', verbose_name='ویژگی ها'),
        ),
    ]
