# Generated by Django 4.0 on 2021-12-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0006_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
