# Generated by Django 3.2.11 on 2022-01-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0007_auto_20220130_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image_id', models.IntegerField(blank=True, default=0, null=True)),
                ('count', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Product.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Product.size')),
            ],
        ),
    ]
