# Generated by Django 4.0 on 2021-12-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
