# Generated by Django 3.2.11 on 2022-01-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0008_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Product.images'),
        ),
    ]
