# Generated by Django 3.2.11 on 2022-01-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0009_alter_variants_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='image_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
