# Generated by Django 4.0 on 2021-12-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0010_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر کالا')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Product.product')),
            ],
        ),
    ]
