# Generated by Django 4.0 on 2021-12-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0011_productdetailslider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetailSlider',
        ),
    ]
