# Generated by Django 4.0 on 2021-12-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0013_productdetailslider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetailSlider',
            new_name='Images',
        ),
    ]
