# Generated by Django 3.2.11 on 2022-01-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0015_auto_20220130_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='Market_Product.Color', verbose_name='رنگ'),
        ),
    ]
