# Generated by Django 4.0 on 2021-12-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0015_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام تگ')),
                ('relation', models.ManyToManyField(to='Market_Product.Product', verbose_name='مرتبط با')),
            ],
        ),
    ]
