# Generated by Django 4.0 on 2022-01-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0016_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='used_in',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='relation',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='Market_Product.Tag', verbose_name='برچسب ها'),
        ),
        migrations.AddField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام برچسب'),
        ),
    ]
