# Generated by Django 3.2.11 on 2022-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0016_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
