# Generated by Django 4.0 on 2022-01-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0017_remove_product_used_in_remove_tag_relation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
