# Generated by Django 4.0 on 2022-01-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Market_Product', '0018_rename_name_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=1)),
                ('comment', models.TextField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('wating_for_published', 'wating_for_published'), ('True', 'True'), ('False', 'False')], max_length=20)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
