# Generated by Django 3.2.11 on 2022-01-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0018_alter_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
