# Generated by Django 4.0 on 2022-01-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0019_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
