# Generated by Django 4.0 on 2022-01-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0020_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('wating_for_published', 'در انتظار تایید'), ('True', 'تایید شده'), ('False', 'تایید نشده')], max_length=20),
        ),
    ]
