# Generated by Django 4.0 on 2022-01-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0021_remove_review_ip_remove_review_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('wating_for_published', 'در انتظار تایید'), ('True', 'تایید شده'), ('False', 'تایید نشده')], default='wating_for_published', max_length=20),
        ),
    ]
