# Generated by Django 3.2.11 on 2022-01-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0022_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Market_Product.Tag', verbose_name='برچسب ها'),
        ),
    ]
