# Generated by Django 3.2.11 on 2022-01-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0023_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10),
        ),
    ]
