# Generated by Django 3.2.11 on 2022-01-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0024_product_medal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام سایز')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='medal',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='Market_Product.Size', verbose_name='برچسب ها'),
        ),
    ]
