# Generated by Django 3.2.11 on 2022-01-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='color',
            field=models.CharField(default='Here Can Be Your Selected Color', max_length=50),
        ),
    ]
