# Generated by Django 4.0 on 2022-01-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0022_alter_review_status'),
        ('Market_Cart', '0002_userfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Product.product'),
        ),
    ]
