# Generated by Django 4.0 on 2022-01-11 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Cart', '0003_alter_userfavorite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market_Cart.order'),
        ),
    ]
