# Generated by Django 3.2.11 on 2022-01-15 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Market_Product', '0023_alter_product_tags'),
        ('Market_Cart', '0006_alter_order_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Market_Cart.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Market_Product.product'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='favorite',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='user',
            field=models.CharField(max_length=250),
        ),
    ]
