# Generated by Django 3.2.11 on 2022-01-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Cart', '0007_auto_20220115_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Market_Cart.order'),
        ),
    ]
