# Generated by Django 3.2.11 on 2022-01-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Cart', '0009_alter_userfavorite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='favorite',
            field=models.CharField(max_length=250),
        ),
    ]
