# Generated by Django 3.2.11 on 2022-01-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Product', '0023_alter_product_tags'),
        ('Market_Cart', '0011_alter_userfavorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Market_Product.product'),
        ),
    ]
