# Generated by Django 3.2.11 on 2022-01-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_Cart', '0012_alter_userfavorite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.CharField(max_length=250),
        ),
    ]
